apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-app
  template:
    metadata:
      labels:
        app: hotel-app
    spec:
      containers:
        - name: hotel-app
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: hotel-secrets
                  key: CONNECTION_STRING
