apiVersion: v1
kind: Secret
metadata:
  name: hotel-secrets
type: Opaque
stringData:
  CONNECTION_STRING: "Server=host.docker.internal,1433;Database=Hotel;User Id=hotel_user;Password=250025;TrustServerCertificate=True;Encrypt=False;"
