pipeline {
  agent any

  environment {
    // For pushing from inside dind (Jenkins network)
    PUSH_REGISTRY = "registry:5000"

    // For Kubernetes pull on Docker Desktop (the one that worked for you)
    K8S_REGISTRY  = "localhost:5000"

    APP_NAME   = "hotel-app"
    IMAGE_TAG  = "${BUILD_NUMBER}-${GIT_COMMIT.take(7)}"

    PUSH_IMAGE = "${PUSH_REGISTRY}/${APP_NAME}:${IMAGE_TAG}"
    K8S_IMAGE  = "${K8S_REGISTRY}/${APP_NAME}:${IMAGE_TAG}"
  }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Build Image') {
      steps {
        dir('Hotel') {
          sh '''
            docker build -t $PUSH_IMAGE .
            docker tag $PUSH_IMAGE $K8S_IMAGE
          '''
        }
      }
    }

    stage('Push to Registry') {
      steps {
        sh '''
          docker push $PUSH_IMAGE
          docker push $K8S_IMAGE
        '''
      }
    }

    stage('Deploy to K8s') {
      steps {
        dir('Hotel') {
          sh '''
            kubectl apply -f k8s/
            kubectl set image deploy/hotel-app hotel-app=$K8S_IMAGE
            kubectl rollout status deploy/hotel-app --timeout=180s
            kubectl get pods -o wide
          '''
        }
      }
    }
  }
}
